name: Entrega continua


on:

  workflow_call:


jobs:


  ECS:

    runs-on: ubuntu-latest


    steps:


      - name: Configurar credenciais AWS

        uses: aws-actions/configure-aws-credentials@v4

        with:

          aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}

          aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}

          aws-region: us-east-2



      - name: Baixar Task Definition

        run: |

          aws ecs describe-task-definition \
            --task-definition Tarefa_API-GO \
            --query taskDefinition \
            > task-definition.json



      - name: Atualizar imagem do container

        id: task-def

        uses: aws-actions/amazon-ecs-render-task-definition@v1

        with:

          task-definition: task-definition.json


          # precisa ser exatamente igual ao nome dentro da AWS ECS

          container-name: Go


          image: evertonhls/curso-ci-4-projeto-inicial:latest



      - name: Deploy ECS

        uses: aws-actions/amazon-ecs-deploy-task-definition@v2

        with:

          task-definition: ${{ steps.task-def.outputs.task-definition }}

          service: Servico_API_Go_CD

          cluster: Api-Go-CD

          wait-for-service-stability: true
