name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  test:
    name: Test Go
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go_version:
          - '1.17'
          - '1.18'

    env:
      HOST: localhost
      DBHOST: localhost
      DBPORT: 5432
      DBUSER: postgres
      DBNAME: postgres
      DBPASSWORD: postgres
      PASSWORD: postgres
      PORT: 8000

    services:
      postgres:
        image: postgres:13

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}


      - name: Baixar dependências
        run: |
          go mod download


      - name: Rodar testes
        run: |
          go test ./...



  build:

    name: Build Docker

    runs-on: ubuntu-latest

    needs: test


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Login Docker Hub
        uses: docker/login-action@v3

        with:
          username: evertonhls
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}


      - name: Build e Push Docker
        uses: docker/build-push-action@v6

        with:

          context: .

          push: true

          tags: |
            evertonhls/curso-ci-4-projeto-inicial:latest
