name: Load Test

on:
  workflow_call:

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout aplicação
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
          aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
          aws-region: us-east-2

      - name: Clonar repositório Infra_CI
        run: |
          git clone https://github.com/EvertonHLS13/Infra_CI.git Infra_CI

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Infra_CI/env/Homolog
        run: terraform init

      - name: Terraform Destroy inicial (limpeza)
        working-directory: Infra_CI/env/Homolog
        continue-on-error: true
        run: terraform destroy -auto-approve

      - name: Terraform Apply
        working-directory: Infra_CI/env/Homolog
        run: terraform apply -auto-approve

      - name: Obter IP do ALB
        id: alb
        working-directory: Infra_CI/env/Homolog
        run: |
          ALB=$(terraform output -raw IP_alb)

          if [ -z "$ALB" ]; then
            echo "Erro: Não foi possível obter o ALB"
            exit 1
          fi

          echo "alb=$ALB" >> "$GITHUB_OUTPUT"

          echo "ALB criado: $ALB"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar Locust
        run: |
          python -m pip install --upgrade pip
          pip install locust

      - name: Criar locustfile.py
        run: |
          cat <<EOF > locustfile.py
          from locust import HttpUser, task, between

          class WebsiteUser(HttpUser):

              wait_time = between(1, 5)

              @task
              def index(self):
                  self.client.get("/")
          EOF

          cat locustfile.py

      - name: Aguardar ALB iniciar
        run: |
          echo "Aguardando Load Balancer ficar disponível..."
          sleep 60

      - name: Executar teste de carga
        run: |
          locust \
            -f locustfile.py \
            --headless \
            -u 10 \
            -r 5 \
            --run-time 60s \
            -H http://${{ steps.alb.outputs.alb }}

      - name: Terraform Destroy final
        if: always()
        working-directory: Infra_CI/env/Homolog
        run: |
          terraform destroy -auto-approve
